# Generated by Django 4.0.4 on 2023-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={'verbose_name_plural': 'chapters'},
        ),
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name_plural': 'devices'},
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'subjects'},
        ),
        migrations.RenameField(
            model_name='chapters',
            old_name='chapter',
            new_name='chapter_name',
        ),
        migrations.AddField(
            model_name='chapters',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
