# Generated by Django 4.0.4 on 2023-02-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0004_alter_chapters_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='description',
        ),
    ]
