# Generated by Django 4.0.4 on 2023-02-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0005_remove_chapters_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='description',
            field=models.TextField(default='Desc'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='chapter_name',
            field=models.CharField(max_length=200),
        ),
    ]
