# Generated by Django 4.0.4 on 2023-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0006_chapters_description_alter_chapters_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subjects',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
