# Generated by Django 4.0.4 on 2023-02-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0007_chapters_image_url_classes_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['Class'], 'verbose_name_plural': 'classes'},
        ),
    ]
