# Generated by Django 4.0.4 on 2023-02-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0009_alter_chapters_options_alter_subjects_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapters',
            unique_together={('chapter_number', 'Class', 'subject')},
        ),
    ]
