# Generated by Django 4.0.4 on 2023-02-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0010_alter_chapters_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('Class',)},
        ),
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together={('subject',)},
        ),
    ]
