# Generated by Django 4.0.4 on 2023-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0011_alter_classes_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='is_enable',
            field=models.BooleanField(default=True),
        ),
    ]
