# Generated by Django 4.0.4 on 2023-02-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0012_alter_devices_is_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
