# Generated by Django 4.0.4 on 2023-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0013_classes_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='s3object_value',
            field=models.TextField(null=True),
        ),
    ]
