# Generated by Django 4.0.4 on 2023-03-11 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s3access', '0013_classes_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='username',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username', unique=True),
        ),
    ]
