# Generated by Django 4.0.4 on 2023-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3access', '0015_alter_chapters_description_alter_chapters_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
